name: Check Commit's Formatting

# This action works with pushes
on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: npm

      - name: Prettify code format
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci --silent --omit optional
          npx prettier --check "**/*.{js,md,html,css}"
